# Generated by Django 4.1.3 on 2022-11-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_db', '0005_profile_start_year_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
